repository: labsyspharm/harvardtissueatlas
imgbaseurl: 'https://tissue-atlas-org.imgix.net/'
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src/js
  - README.md
  - package.json
  - webpack.dev.js
  - webpack.prod.js
  - yarn.lock
permalink: pretty
title: 'Harvard Tissue Atlas'

collections:
  pages:
    output: true
    permalink: /:path
  data-cards:
    output: false
  atlas-datasets:
    output: true
  atlases:
    output: true
    permalink: /atlases/:path
  publications: 
    output: true
  software:
    output: true
  people:
    output: false
  graphics:
    output: false
  funding:
    output: false
  redirects:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ''
      type: data-cards
    values:
      section_id: data
      layout: summary
      heading: Data
      sub_heading: Data Summary
      wide_container: false
  - scope:
      path: ''
      type: atlases
    values:
      section_id: data
      layout: atlas-detail
  - scope:
      path: ''
      type: atlas-datasets
    values:
      wide_container: false
  - scope:
      path: ''
      type: publications
    values:
      section_id: publications
      layout: summary
      heading: Publications
      sub_heading: Publication Summary
      wide_container: false

sass:
  sass_dir: src/_sass
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

# Google Analytics Tracking
ga_tracking: G-Y9Z2ET9707
ga_tracking_anonymize_ip: true